data = [
  {
    id: 5,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 50 MB',
    item_code: 'MD104',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 6,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 150 MB',
    item_code: 'MD105',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 7,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 750 MB',
    item_code: 'MD106',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 8,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 1.5 GB',
    item_code: 'MD107',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 9,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 3.5 GB',
    item_code: 'MD108',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 10,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 5 GB data bundle',
    item_code: 'MD109',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3500
  },
  {
    id: 11,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 35 MB data bundle',
    item_code: 'MD110',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 12,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 100 MB data bundle',
    item_code: 'MD111',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 13,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 800 MB data bundle',
    item_code: 'MD112',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 14,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 1.6GB data bundle',
    item_code: 'MD113',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 15,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 3.75GB data bundle',
    item_code: 'MD114',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 16,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 5GB data bundle',
    item_code: 'MD115',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2500
  },
  {
    id: 17,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 10 MB data bundle',
    item_code: 'MD116',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 50
  },
  {
    id: 18,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 50 MB data bundle',
    item_code: 'MD117',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 19,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 200 MB data bundle',
    item_code: 'MD118',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 20,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 350 MB data bundle',
    item_code: 'MD119',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 300
  },
  {
    id: 21,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 750 MB data bundle',
    item_code: 'MD120',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 22,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 1.3GB data bundle',
    item_code: 'MD121',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 23,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 3.5GB data bundle',
    item_code: 'MD122',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 24,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 5GB data bundle',
    item_code: 'MD123',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2500
  },
  {
    id: 25,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 7GB data bundle',
    item_code: 'MD124',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3500
  },
  {
    id: 26,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 9GB data bundle',
    item_code: 'MD125',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 4000
  },
  {
    id: 27,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 10GB data bundle',
    item_code: 'MD126',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 5000
  },
  {
    id: 28,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 150 MB data bundle',
    item_code: 'MD127',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 29,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 1GB data bundle',
    item_code: 'MD128',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 30,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 1.5GB data bundle',
    item_code: 'MD129',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1200
  },
  {
    id: 31,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 2.5GB data bundle',
    item_code: 'MD130',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 32,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 4GB data bundle',
    item_code: 'MD131',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3000
  },
  {
    id: 33,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 11.5GB data bundle',
    item_code: 'MD132',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 8000
  },
  {
    id: 62,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 50 MB',
    item_code: 'MD104',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 63,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 150 MB',
    item_code: 'MD105',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 64,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 750 MB',
    item_code: 'MD106',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 65,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 1.5 GB',
    item_code: 'MD107',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 66,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 3.5 GB',
    item_code: 'MD108',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 67,
    biller_code: 'BIL104',
    name: 'MTN DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:44.653Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'MTN 5 GB data bundle',
    item_code: 'MD109',
    short_name: 'MTN DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3500
  },
  {
    id: 68,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 35 MB data bundle',
    item_code: 'MD110',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 69,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 100 MB data bundle',
    item_code: 'MD111',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 70,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 800 MB data bundle',
    item_code: 'MD112',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 71,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 1.6GB data bundle',
    item_code: 'MD113',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 72,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 3.75GB data bundle',
    item_code: 'MD114',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 73,
    biller_code: 'BIL105',
    name: 'GLO DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:47.247Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'GLO 5GB data bundle',
    item_code: 'MD115',
    short_name: 'GLO DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2500
  },
  {
    id: 74,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 10 MB data bundle',
    item_code: 'MD116',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 50
  },
  {
    id: 75,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 50 MB data bundle',
    item_code: 'MD117',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 100
  },
  {
    id: 76,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 200 MB data bundle',
    item_code: 'MD118',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 77,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 350 MB data bundle',
    item_code: 'MD119',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 300
  },
  {
    id: 78,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 750 MB data bundle',
    item_code: 'MD120',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 500
  },
  {
    id: 79,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 1.3GB data bundle',
    item_code: 'MD121',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 80,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 3.5GB data bundle',
    item_code: 'MD122',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 81,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 5GB data bundle',
    item_code: 'MD123',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2500
  },
  {
    id: 82,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 7GB data bundle',
    item_code: 'MD124',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3500
  },
  {
    id: 83,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 9GB data bundle',
    item_code: 'MD125',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 4000
  },
  {
    id: 84,
    biller_code: 'BIL106',
    name: 'AIRTEL DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:49.86Z',
    country: 'NG',
    is_airtime: false,
    biller_name: 'AIRTEL 10GB data bundle',
    item_code: 'MD126',
    short_name: 'AIRTEL DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 5000
  },
  {
    id: 85,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 150 MB data bundle',
    item_code: 'MD127',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 200
  },
  {
    id: 86,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 1GB data bundle',
    item_code: 'MD128',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1000
  },
  {
    id: 87,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 1.5GB data bundle',
    item_code: 'MD129',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 1200
  },
  {
    id: 88,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 2.5GB data bundle',
    item_code: 'MD130',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 2000
  },
  {
    id: 89,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 4GB data bundle',
    item_code: 'MD131',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 3000
  },
  {
    id: 90,
    biller_code: 'BIL107',
    name: '9MOBILE DATA BUNDLE',
    default_commission: 0.1,
    date_added: '2020-09-17T15:56:54.737Z',
    country: 'NG',
    is_airtime: false,
    biller_name: '9MOBILE 11.5GB data bundle',
    item_code: 'MD132',
    short_name: '9MOBILE DATA BUNDLE',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 8000
  }
];


airtime = [
  {
    id: 1,
    biller_code: 'BIL099',
    name: 'AIRTIME',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:40.22Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'AIRTIME',
    item_code: 'AT099',
    short_name: 'MTN NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 2,
    biller_code: 'BIL100',
    name: 'AIRTEL NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:41.257Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'AIRTEL VTU',
    item_code: 'AT100',
    short_name: 'AIRTEL NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 3,
    biller_code: 'BIL102',
    name: 'GLO NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:42.173Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'GLO VTU',
    item_code: 'AT102',
    short_name: 'GLO NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 4,
    biller_code: 'BIL103',
    name: '9MOBILE NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:43.093Z',
    country: 'NG',
    is_airtime: true,
    biller_name: '9MOBILE VTU',
    item_code: 'AT103',
    short_name: '9MOBILE NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 58,
    biller_code: 'BIL099',
    name: 'MTN NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:40.22Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'MTN VTU',
    item_code: 'AT099',
    short_name: 'MTN NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 59,
    biller_code: 'BIL100',
    name: 'AIRTEL NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:41.257Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'AIRTEL VTU',
    item_code: 'AT100',
    short_name: 'AIRTEL NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 60,
    biller_code: 'BIL102',
    name: 'GLO NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:42.173Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'GLO VTU',
    item_code: 'AT102',
    short_name: 'GLO NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 61,
    biller_code: 'BIL103',
    name: '9MOBILE NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:43.093Z',
    country: 'NG',
    is_airtime: true,
    biller_name: '9MOBILE VTU',
    item_code: 'AT103',
    short_name: '9MOBILE NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 115,
    biller_code: 'BIL102',
    name: 'GLO NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:42.173Z',
    country: 'NG',
    is_airtime: true,
    biller_name: 'GLO VTU',
    item_code: 'AT133',
    short_name: 'GLO NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  },
  {
    id: 116,
    biller_code: 'BIL103',
    name: '9MOBILE NIGERIA',
    default_commission: 0.03,
    date_added: '2020-09-17T15:56:43.093Z',
    country: 'NG',
    is_airtime: true,
    biller_name: '9MOBILE VTU',
    item_code: 'AT134',
    short_name: '9MOBILE NIGERIA',
    fee: 0,
    commission_on_fee: false,
    label_name: 'Mobile Number',
    amount: 0
  }
]

ng = airtime.filter(plan => {if(plan.country == 'NG') return plan})
console.log(ng)